### ISSUE TITLE
Missing U+1DF8 and U+1DFA in Noto Sans Syriac

### ISSUE THREAD

**Issue by dscorbett** [notofonts/syriac#12]
### Font
NotoSansSyriac-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/9b479a1e7c843da5ea247530a8578f288b49f870/unhinted/otf/NotoSansSyriac/NotoSansSyriac-Regular.otf
Date: 2022-03-07

### Font version
Version 2.000

### Issue
[The Combining Diacritical Marks Supplement code chart](https://www.unicode.org/charts/PDF/U1DC0.pdf) says that U+1DF8 COMBINING DOT ABOVE LEFT and U+1DFA COMBINING DOT BELOW LEFT are “used in Syriac as a disambiguation dot”. Noto Sans Syriac should therefore support them.

### Character data
᷺᷸
U+1DF8 COMBINING DOT ABOVE LEFT
U+1DFA COMBINING DOT BELOW LEFT

**Comment by simoncozens** [comment]
I'm happy to add these but we'd need to think through interactions between them and other dots - particularly U+1DF8 and U+0740 ...

**Comment by iwsfutcmd** [comment]
I can attest that these are indeed used in Syriac. You can find some examples of how they're used in the [proposal](https://www.unicode.org/L2/L2020/20019-syriac-dot-below-left.pdf). There are also links to two sources with extensive usage throughout, if you'd like to see how they interact with other diacritics.

**Comment by simoncozens** [comment]
I've encoded these. I've done it rather naively, using unattached nonspacing marks which sit at a constant height. I think this makes sense for glyphs which are explicitly supposed to be between two other glyphs. If we need to do something more clever with anchors, we might need to come back to it again.
