### ISSUE TITLE
Assyrian Syriac fonts need to be broken up - the merged font set is unusable in most situations

### ISSUE THREAD

**Issue by SargisYonan** [notofonts/syriac#13]
**Font**
NotoSansSyriac

**Font version**
Starting in [v20201206](https://github.com/googlefonts/noto-fonts/releases/tag/v20201206-phase3) I believe

**Issue**
NotoSansSyriac combines Estrangelo, Eastern (_Madenkhaya_), and Western (_Serto_) scripts into one font. These fonts are only distinguishable seemingly by an ISO 15924 system language tag change. Derogatory naming of the ISO 15924 tags aside (SYR-SYR**N** for the eastern font implying the "Nestorian" script; SYR-SYR**J** for the western font implying the "Jacobite" script), they are unusable in mostly any offline application. 

e.g. how would one differentiate which font they'd like to use when the font is installed offline and used in a word processor?

Outside of a web environment, the newer thin and bold faced Eastern and Western script fonts are effectively unusable.

Please consider separating the fonts into 3 separate fonts once again.

**Comment by simoncozens** [comment]
Let's move this to #10.
