### ISSUE TITLE
Final Semkath [U+0724] rendered incorrectly when connected

### ISSUE THREAD

**Issue by SargisYonan** [notofonts/syriac#27]
### Title 
Final Semkath [U+0724] not rendering correctly when connected to another letter

### Font 
NotoSansSyriac[wght].ttf
https://notofonts.github.io/syriac/fonts/NotoSansSyriac/unhinted/variable/NotoSansSyriac[wght].ttf

### Where the font came from, and when
Site: https://notofonts.github.io/syriac/fonts/NotoSansSyriac/unhinted/variable/NotoSansSyriac[wght].ttf
Date: 2024-05-09

### Font Version
[NotoSansSyriac-v3.000](https://github.com/notofonts/syriac/releases/tag/NotoSansSyriac-v3.000)

### OS name and version
macOS 14.0

### Application name and version
Pages.app & the type tester in Safari here: https://fonts.google.com/noto/specimen/Noto+Sans+Syriac

### Issue
The latest Noto font version fixes the shape of U+0724 final semkath, and it is correctly drawn when in an isolated state. When the character is connected to any other letter, it is not drawn correctly. It appears as a non-final Semkath [U+0723] when it should instead have the final form (with the line down the middle). Note, I did not observe this incorrect behavior on the eastern variant of the Noto font.

**Steps to reproduce**
Go to the type tester at https://fonts.google.com/noto/specimen/Noto+Sans+Syriac and type [U+0724] on one line. Then on another line, type both Semkaths [U+0723] and [U+0724]

**Observed Results**
The final semkath does not have the line going down the middle when it connects to the non-final Semkath. When isolated, it does have the line down the middle.

<img width="309" alt="Actual_Incorrect" src="https://github.com/notofonts/syriac/assets/5349027/32c68495-f68b-4bab-8d27-89d8b7a036c8">

**Expected Results**
The connected final-semkath should have a line down the middle when connected from the right.

<img width="303" alt="Expected" src="https://github.com/notofonts/syriac/assets/5349027/318b36d0-d493-471e-ac7d-6edf96480a07">

**Comment by SargisYonan** [comment]
This needs to only be fixed for the final version of the glyph since it should only apply in the final form. Attached is a path to fix the issue:

```
diff --git a/sources/NotoSansSyriac.glyphs b/sources/NotoSansSyriac.glyphs
index 1723ce0..c3a8db5 100644
--- a/sources/NotoSansSyriac.glyphs
+++ b/sources/NotoSansSyriac.glyphs
@@ -1,10 +1,12 @@
 {
-.appVersion = "3243";
+.appVersion = "3259";
 .formatVersion = 3;
 DisplayStrings = (
 "/uni072B.fina",
 "/uni0712.init",
-"᷺/uni071B.init.longG"
+"᷺/uni071B.init.longG",
+"ܤ",
+"/uni0724.fina"
 );
 axes = (
 {
@@ -15435,7 +15437,7 @@ unicode = 1828;
 },
 {
 glyphname = uni0724.fina;
-lastChange = "2022-12-15 11:31:32 +0000";
+lastChange = "2024-05-21 08:05:26 +0000";
 layers = (
 {
 anchors = (
@@ -15511,6 +15513,15 @@ nodes = (
 (687,76,o),
 (574,76,cs)
 );
+},
+{
+closed = 1;
+nodes = (
+(418,-70,l),
+(491,-70,l),
+(490,5,l),
+(418,5,l)
+);
 }
 );
 width = 891;
```

**Comment by iwsfutcmd** [comment]
Good catch, I've made a PR (#29) to fix this. I had to modify your patch slightly to apply to all of the weights.
