### ISSUE TITLE
Nominal glyph  for U+0740 (Syriac Feminine Dot) is too close to the baseline and can be confused for full-stop

### ISSUE THREAD

**Issue by brawer** [notofonts/syriac#3]
U+0740 SYRIAC FEMININE DOT should be positioned high up. Currently it’s at the baseline, so it looks like a full stop.

**Comment by simoncozens** [comment]
This seems to have been fixed; U+0740 is anchored on the top left of all consonants (and the dotted circle) using the `top` anchor.

![shape](https://user-images.githubusercontent.com/106728/210248425-275a50c4-8d18-46ba-8ff5-74454981f89b.png)
