### ISSUE TITLE
U+2044 FRACTION SLASH in Noto Sans Syriac

### ISSUE THREAD

**Issue by dscorbett** [notofonts/syriac#9]
### Font
NotoSansSyriac-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/unhinted/NotoSansSyriac/NotoSansSyriac-Regular.ttf
Date: 2020-03-29

### Font version
Version 2.000

### Issue
U+2044 FRACTION SLASH is supposed to compose adjacent digits into vulgar fractions. In this font it does nothing. If Syriac uses vulgar fractions, U+2044 should create them; if not, U+2044 should not be in the font.

### Character data
٣⁄٤
U+0663 ARABIC-INDIC DIGIT THREE
U+2044 FRACTION SLASH
U+0664 ARABIC-INDIC DIGIT FOUR

### Screenshot
![٣⁄٤](https://user-images.githubusercontent.com/1124347/77851080-d0cea400-71a4-11ea-995c-8e759ce5450d.png)

**Comment by SKing-2003** [comment]
Some further input on this would be appreciated.

**Comment by simoncozens** [comment]
I'm removing the fraction slash. It strikes me that we don't actually have any digits in this font.
